version=0.1
 [default.global.parameters]
 stack_name = "gates-dev"
 
 [default.deploy.parameters]
 stack_name = "gates-dev"
 s3_bucket = "gates-dev-sam-package"
 region = "ap-northeast-1"
 confirm_changeset = true
 capabilities = "CAPABILITY_IAM"
 tags = "project=\"gates\" stage=\"dev\""
