AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: gates
  Environment:
    Type: String
    Default: dev
  ApiKey:
    Type: String

Resources:
  gatesArticleCrawler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-news_crawler
      CodeUri: functions/
      Handler: news_crawler.lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${ProjectName}-${Environment}
      Layers:
        - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:7
      Environment:
        Variables:
          API_KEY: !Sub ${ApiKey}
          DB_TABLE_NAME: !Sub ${ProjectName}-${Environment}
      Events:
        Schedule:
          Type: Schedule 
          Properties:
            Name: !Sub ${ProjectName}-${Environment}-news_crawler-trigger
            Schedule: cron(0 18 * * ? *)
  gatesGetNews:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-get-news
      CodeUri: functions/
      Handler: retrieve_news.lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${ProjectName}-${Environment}
      Environment:
        Variables:
          DB_TABLE_NAME: !Sub ${ProjectName}-${Environment}
