AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  ProjectName:
    Type: String
    Default: gates
  Environment:
    Type: String
    Default: dev
  ApiKey:
    Type: String
Resources:
  gatesArticleCrawler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ProjectName}-${Environment}-news_crawler
      CodeUri: s3://gates-dev-sam-package/6fd42f3bbe40833808c929e7203fa349
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 90
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::Sub: ${ProjectName}-${Environment}
      Layers:
      - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:7
      Environment:
        Variables:
          API_KEY:
            Fn::Sub: ${ApiKey}
          DB_TABLE_NAME:
            Fn::Sub: ${ProjectName}-${Environment}
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Name:
              Fn::Sub: ${ProjectName}-${Environment}-news_crawler-trigger
            Schedule: cron(0 * * * ? *)
